name = "Tectonic Cliftree"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16d170295b078eec53802038c79a94b71b9b5158db59f6f38fa6238cc0149738"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
