name = "Tectonic Cliftree"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74bb2f1151e891b0cf0d984e0913edca33708e12c6b716da07a15c68cca6b902"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
